displayName=BA Wave Info
author=sonny
description=Infobox to track spawn numbers per wave for each role in BA
tags=BA, Barbarian, Assault, ba, Barbarian Assault, barbarian assault
version=1.0.0
plugins=com.bawaveinfo.BaWaveInfoPlugin
build=standard